# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
success_symbol = '[➜](bold green)' # The "success_symbol" segment is being set to "➜" with the color "bold green"

[line_break]
disabled = true

[cmd_duration]
disabled = true # using the zsh timer instead

[directory]
read_only = " "

[git_branch]
symbol = " "

[hostname]
ssh_only = true
format = '[\[$hostname\]]($style) ' # Looks better without the symbol

[nix_shell]
format = 'via [$symbol$name]($style) ' # Removed state impure / pure

[package]
disabled = true # Package version is rarely useful

[rust]
format = 'via [$symbol($version \($toolchain\) )]($style)'

[terraform]
disabled = true # Don't really care about the terraform workspace
